name: Manual Version Bump

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Semver increment type for npm version"
        required: true
        type: choice
        options:
          - prepatch
          - patch
          - preminor
          - minor
          - premajor
          - prerelease

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configure Git author
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Run npm version
        run: |
          npm install --package-lock-only --ignore-scripts  # ensure lockfile exists
          npm version ${{ github.event.inputs.release_type }}

      - name: Push commit & tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --follow-tags
